// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TerminalsImport } from './routes/terminals'
import { Route as LoginImport } from './routes/login'
import { Route as TerminalTerminalIdImport } from './routes/terminal.$terminalId'
import { Route as DefectDefectIdImport } from './routes/defect.$defectId'

// Create/Update Routes

const TerminalsRoute = TerminalsImport.update({
  path: '/terminals',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const TerminalTerminalIdRoute = TerminalTerminalIdImport.update({
  path: '/terminal/$terminalId',
  getParentRoute: () => rootRoute,
} as any)

const DefectDefectIdRoute = DefectDefectIdImport.update({
  path: '/defect/$defectId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/terminals': {
      preLoaderRoute: typeof TerminalsImport
      parentRoute: typeof rootRoute
    }
    '/defect/$defectId': {
      preLoaderRoute: typeof DefectDefectIdImport
      parentRoute: typeof rootRoute
    }
    '/terminal/$terminalId': {
      preLoaderRoute: typeof TerminalTerminalIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LoginRoute,
  TerminalsRoute,
  DefectDefectIdRoute,
  TerminalTerminalIdRoute,
])
